FROM uninen/python:3.13

ENV DOCKER_BUILDKIT=1

WORKDIR /code
ADD . /code

RUN --mount=type=cache,target=/root/.cache \
    uv pip install -r requirements.txt

CMD ["uvicorn", "--host", "0.0.0.0", "hello:app"]
