name: Dev

on:
  workflow_run:
    workflows: [build-311-postgis-node]
    types: [completed]
  workflow_call:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: python-postgis-node-dev.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: uninen/python-postgis-node-dev:latest
