name: Build Node 20

on:
  pull_request:
    paths:
      - .github/workflows/build-node-20.yml
      - .github/workflows/push-node-20.yml
      - node-20.Dockerfile
      - scripts/cleanup.sh
      - scripts/install-common.sh
      - scripts/prep-node.sh

concurrency:
  group: build-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: node-20.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: uninen/node:20
