name: build-python-dev
run-name: Build Python DEV

on:
  workflow_run:
    workflows: [build-postgis-node]
    types: [completed]
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v6.10.0
        with:
          file: python-dev.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: uninen/python-dev:latest
