name: Build Python 3.12

on:
  pull_request:
    paths:
      - .github/workflows/build-python-3.12.yml
      - python-3.12.Dockerfile
      - scripts/cleanup.sh
      - scripts/install-common.sh
      - scripts/install-postgres-client.sh
      - scripts/prep-python.sh

concurrency:
  group: build-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: python-3.12.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
          tags: uninen/python:3.12
