name: push-postgis-node
run-name: Push Python 3.13 + Postgis + Node

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/push-python-postgis-node.yml
      - python-postgis-node.Dockerfile
      - scripts/cleanup.sh
      - scripts/install-common.sh
      - scripts/install-postgres-client.sh
      - scripts/install-audiowaveform.sh
      - scripts/prep-postgis-node.sh
  schedule:
    - cron: 5 6 22 * * # every 22nd on 5.55 UTC
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.5.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6.10.0
        with:
          file: python-postgis-node.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: uninen/python-postgis-node:3.13
