name: Push Python 3.12

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/push-python-3.12.yml
      - python-3.12.Dockerfile
      - scripts/cleanup.sh
      - scripts/install-common.sh
      - scripts/install-postgres-client.sh
      - scripts/prep-python.sh
  schedule:
    - cron: 55 5 22 * * # every 22nd on 5.55 UTC
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          file: python-3.12.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: uninen/python:3.12
