name: Push Node 20

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/push-node-20.yml
      - node-20.Dockerfile
      - scripts/cleanup.sh
      - scripts/install-common.sh
      - scripts/prep-node.sh
  schedule:
    - cron: 45 5 22 * * # every 22nd on 5.55 UTC
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: node-20.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: uninen/node:20
