name: push-311-postgis
run-name: Push Python 3.11 + Postgis

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/python-postgis-3.11.yml
      - python-postgis-3.11.Dockerfile
      - scripts/install-audiowaveform.sh
      - scripts/install-deps-postgis.sh
  schedule:
    - cron: 59 5 22 * * # every 22nd on 5.55 UTC
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: python-postgis-3.11.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: uninen/python-postgis:3.11
