name: Dev

on:
  workflow_run:
    workflows: [Python 3.11 + Postgis + Node]
    types: [completed]
  workflow_dispatch:

concurrency:
  group: front-${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: python-postgis-node-dev.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: uninen/python-postgis-node-dev:latest
